# Generated by Django 3.0.5 on 2020-04-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('lcount', models.IntegerField()),
                ('active', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deceased', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('age', models.IntegerField()),
                ('locality', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
                ('rdate', models.DateField()),
            ],
        ),
    ]
