# Generated by Django 3.0.5 on 2020-04-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='district',
            name='deceased',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='district',
            name='lcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='district',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
    ]
